### ISSUE TITLE
SSH Certificates instead of OTP?

### ISSUE THREAD

**Issue by gardar** [konstruktoid/ansible-hvault-inventory#97]
Hi.

Wondering if you had explored the possibility of using short lived SSH certificates from vault instead of otp?

**Comment by konstruktoid** [comment]
Hi @gardar, I have but not as a part of an inventory script. Interesting idea though.

**Comment by konstruktoid** [comment]
I was wondering what would you store in the inventory regarding short lived SSH certificates.
Requesting SSH certs are managed by the user and the vault key is publicly available

**Comment by gardar** [comment]
Are you talking about what the user should place in the kv inventory? Or what the output should be?

For the output you'd need to set both the key and certificate, the key would be in `ansible_private_key_file` and the certificate then probably needs to be set in `ansible_ssh_common_args`

Perhaps this could be used for inspiration: https://github.com/candlerb/vault-ssh-agent-login

**Comment by konstruktoid** [comment]
https://github.com/candlerb/vault-ssh-agent-login/blob/main/main.go#L23-L28, so when using `vault-ssh-agent-login` the secret key isn't stored anywhere which is a good thing, but everything is handled locally except the signing part.

what part of https://developer.hashicorp.com/vault/docs/secrets/ssh/signed-ssh-certificates#client-ssh-authentication should be handled by the inventory and what part should be handled by the user?

**Comment by gardar** [comment]
If you are using the certificates with a low ttl and using principals (as suggested here: https://www.hashicorp.com/blog/managing-ssh-access-at-scale-with-hashicorp-vault )
then I don't think you need to generate or store the public/private keys for the user and in fact I'm not sure there is much security gain from generating the keys for the user as they are basically useless without the certificate (that is if you only use the key for certificate auth).

The user will provide it's own public key and principal (the principal should perhaps match `ansible_user`) to the inventory and then the inventory contacts vault for signing the key and returning the certificate.
So the user public key is static but the certificate is dynamic and the inventory needs to understand the ttl of the certificate and rotate it as required.

**Comment by konstruktoid** [comment]
something like this?
- add `ansible_user` and the `ansible_user` public key; `ansible_ssh_public_key_file` 
- the inventory script the signs `ansible_ssh_public_key_file`  and turns it into `ansible_ssh_signed_public_key_file`.
- in order to log in the `ansible_user` needs to supply the `ansible_ssh_private_key_file` (stored locally) and `ansible_ssh_signed_public_key_file` (stored in vault).

**Comment by gardar** [comment]
Yep that should work!

The manual workflow is something like:

```
vault write -field=signed_key ssh-client-signer/sign/myuser-role public_key=@$HOME/.ssh/id_rsa.pub valid_principals=myuser > ~/.ssh/id_rsa-signed.pub

ssh -i ~/.ssh/id_rsa -i ~/.ssh/id_rsa-signed.pub myuser@domain
```

**Comment by konstruktoid** [comment]
Sorry for the delay, I just haven't had the time to work on this yet.

**Comment by gardar** [comment]
No stress about the delay! I totally get that you're swamped. It's cool that you're even considering my idea. Take all the time you need and thanks for keeping me in the loop!

**Comment by konstruktoid** [comment]
Basic docs done, and writing code has begun.

**Comment by konstruktoid** [comment]
I've made https://github.com/konstruktoid/ansible-hvault-inventory/pull/104 which adds signed SSH cert support, but I need to rewrite some docs I believe and not sure about the logic since you need to run the inventory script to refresh the cert initially

**Comment by konstruktoid** [comment]
merged

**Comment by gardar** [comment]
Awesome! Didn't have a chance to test #104 but I'll be testing the merged version soon!
